AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Cloudformation template to create network resources required for a 3-tier architecture."

Transform: AWS::LanguageExtensions

Parameters:
  VpcCidr:
    Type: "String"
    Default: 10.0.0.0/20
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "Must be a valid IPv4 CIDR range of the form x.x.x.x/x."
  NumberOfAZs:
    Type: String
    AllowedPattern: "[2-3]"
    Default: 2 # This is because the ALB needs subnets in at least 2 AZs
  ServiceName:
    Type: String
    Default: testing


Resources:
  NetworkResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcCidr: !Ref VpcCidr
        NumberOfAZs: !Ref NumberOfAZs
      Tags: 
        - Key: Service
          Value: !Ref ServiceName
      TemplateURL: 
        https://portfolio-cloudformation-templates.s3.amazonaws.com/network-template.yaml

  ServiceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Sub '${ServiceName}ALB'
      SecurityGroups: 
        - !GetAtt NetworkResources.Outputs.ALBSecurityGroup
      Subnets: 
        Fn::Transform:
          Name: GenerateSequence
          Parameters:
            identifier: Identifier
            start: 0
            stop: !Ref NumberOfAZs
        Fn::GetAtt:
          - NetworkResources
          - !Sub 'Outputs.PublicSubnets${Identifier}'
      Tags: 
        - Key: Application
          Value: !Ref ServiceName
      Type: application

  ServiceAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: # Required
        - TargetGroupArn: !Ref ServiceTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ServiceALB # Required
      Port: 80
      Protocol: HTTP
      
  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      Name: !Sub '${ServiceName}-TargetGroup'
      Port: 80
      Protocol: HTTP
      Tags: 
        - Key: Service
          Value: !Ref ServiceName
      TargetType: instance
      VpcId: !GetAtt NetworkResources.Outputs.AppVpcId

  ServiceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        #IamInstanceProfile:
        #  Arn: "String"
        #  Name: "String"
        ImageId: 'ami-0b72821e2f351e396'
        InstanceType: t2.micro
        SecurityGroupIds:
          - !GetAtt NetworkResources.Outputs.PrivateAccessSecurityGroup
        UserData: 
          Fn::Base64: |
            #!/bin/bash
            # Use this for your user data (script from top to bottom)
            # install httpd (Linux 2 version)
            yum update -y
            yum install -y httpd
              
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
      LaunchTemplateName: !Sub '${ServiceName}-LaunchTemplate'

  ServiceASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub '${ServiceName}-ASG'
      DefaultInstanceWarmup: 0
      DesiredCapacity: 2
      HealthCheckGracePeriod: 5
      LaunchTemplate:
        LaunchTemplateId: !Ref ServiceLaunchTemplate
        Version: !GetAtt ServiceLaunchTemplate.LatestVersionNumber
      MaxSize: 6 # Required
      MinSize: 1 # Required
      TargetGroupARNs: 
        - !Ref ServiceTargetGroup
      VPCZoneIdentifier: 
        Fn::Transform:
          Name: GenerateSequence
          Parameters:
            identifier: Identifier
            start: 0
            stop: !Ref NumberOfAZs
        Fn::GetAtt:
          - NetworkResources
          - !Sub 'Outputs.PrivateSubnets${Identifier}'
    
  ServiceASGPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ServiceASG # Required
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        DisableScaleIn: false
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 60


Outputs:
  ServiceAlbDNSName:
    Description: 'The DNS name of application load balancer of the service'
    Value: !Join
        - ''
        - - 'http://'
          - Fn::GetAtt: ServiceALB.DNSName
    Export:
      Name: !Sub '${ServiceName}-ALB-DNSName'
